# ~/.config/hypr/monitors.conf

# Define your monitor variables
$main = HDMI-A-2
$second = DP-1

# Apply the monitor configuration using the variables
# monitor = name, resolution, position, scale
monitor = $main, 1920x1080@60, 0x0, 1
monitor = $second, 1920x1080@60, 1920x0, 1
