# ~/.config/hypr/workspaces.conf

# Laptop Workspaces
workspace = 1, monitor:$main, default:true
workspace = 2, monitor:$main
workspace = 3, monitor:$main
workspace = 4, monitor:$main
workspace = 5, monitor:$main

# External Monitor Workspaces
workspace = 6, monitor:$second, default:true
workspace = 7, monitor:$second
workspace = 8, monitor:$second
workspace = 9, monitor:$second
workspace = 10, monitor:$second
